# Generated by Django 5.1.5 on 2025-01-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='Zoir@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Zoir', max_length=100),
        ),
    ]
