# Generated by Django 5.1.5 on 2025-01-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='Zoir@gmail.com', max_length=254),
        ),
    ]
