# Generated by Django 5.1.5 on 2025-01-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
