# Generated by Django 5.1.5 on 2025-01-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_catalog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='slug',
        ),
    ]
